# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name of course'),
        ),
    ]
